### ISSUE TITLE
Add the steps to install this Project in `Readme.md`

### ISSUE THREAD

**Issue by Coollaitar** [ethereum-push-notification-service/push-dapp#1015]

**Comment by Coollaitar** [comment]
> ### Expected Behaviour
> _No response_
> 
> ### Current Behaviour
> _No response_
> 
> ### Steps to Reproduce
> _No response_

I was facing an issue while installing this project on VS code that's why raise this issue.

**Comment by Coollaitar** [comment]
> Hey @Coollaitar, to run this repo in local, you just need to clone the repo and run these commands: 1> `yarn install` 2> `yarn start`
> 
> Do let me know, if you're facing any specific issue Thanks

I'm getting too many errors!
![errors](https://user-images.githubusercontent.com/94162491/229546819-36380753-c7a0-4ed7-9d8b-8fd2cda22ff4.jpg)

**Comment by corlard3y** [comment]
Hi @Coollaitar Delete your node_modules file, and yarn.lock file and follow these steps again in the root directory of your folder.
- yarn install
- yarn start
Also, to be sure your setup is okay, do you have an .env file from your .env sample file???

**Comment by Coollaitar** [comment]
> 
Thanks, now errors from many decreased to 3 ps help me out!
![error2](https://user-images.githubusercontent.com/94162491/229810894-57e07a3b-aecd-4b79-9232-55397332264d.jpg)

**Comment by Coollaitar** [comment]
> > 
> 
> Thanks, now errors from many decreased to 3 ps help me out! ![error2](https://user-images.githubusercontent.com/94162491/229810894-57e07a3b-aecd-4b79-9232-55397332264d.jpg)

Getting the below error
`Unexpected token 'd', "dark" is not valid JSON
SyntaxError: Unexpected token 'd', "dark" is not valid JSON
    at JSON.parse (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:2244:24
    at invokePassiveEffectCreate (http://localhost:3000/static/js/bundle.js:242492:24)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:225790:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:225834:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:225889:35)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:242562:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/bundle.js:362300:16)
    at runWithPriority$1 (http://localhost:3000/static/js/bundle.js:232126:14)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:242458:18)`

**Comment by corlard3y** [comment]
Do you have an .env content? If yes, can you share the content with me. You can send to my email koladeo@epns.io if you do not wanna post it here.

**Comment by corlard3y** [comment]
Trying to update the readme using this issue @Coollaitar ,so it will be closed after that is completed

**Comment by Coollaitar** [comment]
> Trying to update the readme using this issue @Coollaitar ,so it will be closed after that is completed

Okay ser!
