### ISSUE TITLE
🚀 [New Feature] - Implement space preview in chat

### ISSUE THREAD

**Issue by mishramonalisha76** [ethereum-push-notification-service/push-dapp#1077]
### Describe the Feature

Implement space preview in chat

### Figma Design if available

https://www.figma.com/file/PzAmXUMOmwS2ljxufwv44m/PUSH-Prototypes?node-id=10823-41736&t=WLay0ZqCYg7UeoPT-0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by abhishek-01k** [comment]
This can be closed @mishramonalisha76 as this is done.
CC: @zaryab2000
