### ISSUE TITLE
🎨 [UI/UX Enhancement] - Fix UI of Ongoing Call screen

### ISSUE THREAD

**Issue by madhur-push** [ethereum-push-notification-service/push-dapp#1136]
### Expected UI

- Should be according to the figma design.

### Current UI

- The name/address tag on the bottom left of the incoming video is not correct atm, need to be replaced with he current UI.
- Fix the positioning of local video (bottom right) as per figma design for screen widths.
- Add a bit of margin over the call buttons
- Border radius are incorrect for mobile screen

### Figma Design if available

https://www.figma.com/file/PzAmXUMOmwS2ljxufwv44m/PUSH-Prototypes?type=design&node-id=10100%3A29582&t=aMvxUaX6C7WsnLbW-1

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by KlausMikhaelson** [comment]
#1145
