### ISSUE TITLE
🎨 [UI/UX Enhancement] - IncomingVideo being cropped off

### ISSUE THREAD

**Issue by KlausMikhaelson** [ethereum-push-notification-service/push-dapp#1146]
### Expected UI

When we go below 768px than the video starts cropping off from right
for e.x. if we are on 300px like the ss below if we are exactly in front of the camera than still will look like we are not in centered

### Current UI

<img width="416" alt="image" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/100528412/d57035a8-5140-4f96-b96f-283dbaba6dc2">

### Steps to Reproduce

```bash
1. Go to 'chat'
2. Click on 'video call'
3. Scroll down to 'decrease width below 768px'
4. See UI
```

### Expected UI Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Current UI Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org)

**Comment by madhur-push** [comment]
Duplicate issue, closing it, #1137 will take care of this.
