### ISSUE TITLE
🎨 [UI/UX Enhancement] - fix dark theme for message input and chat profile component

### ISSUE THREAD

**Issue by KlausMikhaelson** [ethereum-push-notification-service/push-dapp#1370]
### Current UI

it is not matching the dark theme

### Steps to Reproduce

```bash
1. Go to 'chats'
2. Click on 'any user/group'
3. turn on dark mode
4. See UI
```

### Expected UI Screenshots

```bash
It should match the dark theme
```

### Current UI Screenshots

<img width="1294" alt="Screenshot 2024-01-05 at 6 51 54 AM" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/100528412/c2dd28cb-cc3f-4acf-a9fb-86af3145e598">

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by pritipsingh** [comment]
This is fixed, so closing this!
