### ISSUE TITLE
✏️ [Documentation/Readme Enhancement] - <Wrong Repo Setup>

### ISSUE THREAD

**Issue by kamuik16** [ethereum-push-notification-service/push-dapp#1391]
### Expected Behaviour

When setting up a repository, it is standard practice to first fork the repository to one's personal GitHub account and then clone it from there. The expected setup instructions in the `contributing.md` and `README.md` files should guide contributors to fork the repository first and then use the correct clone command.

1. Fork the repository to their personal GitHub account.
2. Clone the forked repository using the correct command:
```bash
git clone https://github.com/your-username/push-dapp
```

### Current Behaviour

The current contributing.md and README.md file in the push-dapp repository does not instruct users to fork the repository. Additionally, it provides an incorrect clone command. The current instructions are:
```bash
git clone https://github.com/ethereum-push-notification-service/push-dapp
```

### Steps to Reproduce

```bash
1. Go to 'README.md and contributing.md file'
```

**Comment by kamuik16** [comment]
I would be happy to raise a PR for this!

**Comment by pritipsingh** [comment]
Thanks for pointing this out @kamuik16 . You can take this up! Assigned it to you!

**Comment by kamuik16** [comment]
> Thanks for pointing this out @kamuik16 . You can take this up! Assigned it to you!

Hey @pritipsingh! Opened this https://github.com/ethereum-push-notification-service/push-dapp/pull/1394 PR. Let me know if you want any changes.
