### ISSUE TITLE
🐛 [BUG] - <Chat Messages not loading and error in send message>

### ISSUE THREAD

**Issue by Siddesh7** [ethereum-push-notification-service/push-dapp#1444]
### Expected Behaviour

It should be fetching the chats and should be able to send message to a chat

### Current Behaviour

but it doesnt work,

I can see,

- I see `encType` undefined error in console.
- Idk why there is 100s of constant RPC pings, (is this intended or a bug?)
 

https://github.com/ethereum-push-notification-service/push-dapp/assets/79219618/4c1d81e8-7a20-4828-a3be-d3efc85affd5

### Reproduction steps

```bash
na
```

### Dapp Env

Staging (staging.push.org)

**Comment by Aman035** [comment]
This issue was caused due to Push node change.
Should be fixed now
