### ISSUE TITLE
Replace react context with redux in w2w part of code

### ISSUE THREAD

**Issue by 0xNilesh** [ethereum-push-notification-service/push-dapp#510]

**Comment by 0xNilesh** [comment]
https://docs.google.com/document/d/18RhHoVy4BqLanf7kQ8T7XqK8gKNmEFudXhVHl7NWfVg/edit?usp=sharing

**Comment by zaryab2000** [comment]
Closing this issue, since we have a consensus to move forward with Context as of now 

cc: @HarshRajat @0xNilesh @mishramonalisha76
