### ISSUE TITLE
Display ens avatar if any instead of default image

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#544]

**Comment by b4s36t4** [comment]
Can any body assign this to me?!

**Comment by bhagyamudgal** [comment]
Can I work on this?

**Comment by codedbyjordan** [comment]
I feel like I'd be a good fit to work on this, I have good knowledge of TypeScript and I work as a full-time web3 developer so I have hands-on experience in the field.

**Comment by DAOminds** [comment]
looks like a lot of learnweb users want to participate here
