### ISSUE TITLE
Create default 404 page

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#549]
When going to a random path, we get this page

<img width="887" alt="image" src="https://user-images.githubusercontent.com/19648581/197289424-77af086d-b503-4acc-a151-a8fad75328a3.png">

**Comment by Wholesomebruh** [comment]
What should the new page look like?

**Comment by route-2** [comment]
https://github.com/ethereum-push-notification-service/push-dapp/pull/1357
