### ISSUE TITLE
Issue on inbox notifications without cta

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#574]
Notifications that don't have cta are allowing users to click on them and to get redirected to a link of a cta from one of the notifications in the inbox

Although the UI doesn't show the blue circle around the notification since the notification doesn't have a cta, users can still click on the notification and are redirected to a cta of one of the notifications that are being displayed in their inbox

In the image below the notification doesn't have a cta, but the user can click on it the user gets redirected

<img width="452" alt="image" src="https://user-images.githubusercontent.com/19648581/199718983-a28e24b8-486c-4db8-bfe3-f2bd04de17d8.png">

**Comment by corlard3y** [comment]
So this issue was created twice, and i will be closing for that reason
