### ISSUE TITLE
Chat messages dont update properly ,when a particular chatbox is open

### ISSUE THREAD

**Issue by mishramonalisha76** [ethereum-push-notification-service/push-dapp#594]

**Comment by zaryab2000** [comment]
@mishramonalisha76 is this something we are working on currently - or is paused?

**Comment by mishramonalisha76** [comment]
We can proceed with this once wbesockets for receiving message is done from sdk side

**Comment by zaryab2000** [comment]
alright - this shall start with optimization milestone as well then
