### ISSUE TITLE
Notifications without cta are being displayed with cta with the link from the channel url

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#632]
Notifications without cta are allowing users to click on them and get redirected to the channel url

**Comment by madhurg-epns** [comment]
- For Channel URL:
  - Change the entire grey area being clickable to only the channel name being clickable.
  - Also, change the color of channel name upon hover.

- For CTA URL:
  - Maybe we can add a CTA link button in the notif body. (To be decided)
  
  cc: @zaryab2000 @zeepush

**Comment by zaryab2000** [comment]
@zeepush , if you have an update on this, do share
