### ISSUE TITLE
Resolving ENS on chat is taking too long

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#646]

**Comment by mishramonalisha76** [comment]
We can change the provider url to our infura or Alchemy account instead of the default provider from ethers to resolve the ens

**Comment by zaryab2000** [comment]
@mishramonalisha76 @abhishek-01k  - is the PR #659 currently under QA?

**Comment by mishramonalisha76** [comment]
> @mishramonalisha76 @abhishek-01k - is the PR #659 currently under QA?

Yes this is under review

**Comment by zaryab2000** [comment]
Alright @mishramonalisha76
