### ISSUE TITLE
Optimize twitter preview feature in chat

### ISSUE THREAD

**Issue by deekshithepns** [ethereum-push-notification-service/push-dapp#652]
customize the twitter preview card

**Comment by zaryab2000** [comment]
@deekshithepns Quick check -

Is this a duplication of this issue #651 ? or is it a new one?

If this is a new one, might be good to add some description to it

**Comment by deekshithepns** [comment]
> @deekshithepns Quick check -
> 
> Is this a duplication of this issue #651 ? or is it a new one?
> 
> If this is a new one, might be good to add some description to it

Yes... This is new one, Fabio asked to create this one.

**Comment by zaryab2000** [comment]
@deekshithepns let me know if this can be closed now? what's the status of this issue as of now?

**Comment by deekshithepns** [comment]
> @deekshithepns let me know if this can be closed now? what's the status of this issue as of now?

This issue not yet taken up, fabio asked to create it, so that if anyone have bandwidth they can take up and work on it.

**Comment by zaryab2000** [comment]
noted. Thanks @deekshithepns 

@0xNilesh @mishramonalisha76 moving to this our Dapp Optimization milestone under backlog minors category
