### ISSUE TITLE
Fix text when approving intent

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-dapp#657]
The text is not correct

![image](https://user-images.githubusercontent.com/19648581/208781537-c2d4e477-85cc-4f6d-bdc8-bc55baea61cc.png)

**Comment by mishramonalisha76** [comment]
if receiver of the message has pgp keys then: Messages are encrypted
else, we use the message above

**Comment by mishramonalisha76** [comment]
ETA- 9/02/23 2pm ist

**Comment by 0xNilesh** [comment]
Seems like, it's addressed now
