### ISSUE TITLE
Add signature in payload for chat api calls

### ISSUE THREAD

**Issue by mishramonalisha76** [ethereum-push-notification-service/push-dapp#667]

**Comment by zaryab2000** [comment]
@mishramonalisha76 have we started working on this one yet? better to assign one dev to this

**Comment by mishramonalisha76** [comment]
@zaryab2000  this is a parent issue, for now the push node has support for signature validation only for create user, for which https://github.com/ethereum-push-notification-service/push-dapp/issues/419 this is the issue. So we will start working on create-user isseu first.

**Comment by mishramonalisha76** [comment]
This will be  in sdk
