### ISSUE TITLE
Inbox and Spam page are not scrollable

### ISSUE THREAD

**Issue by madhurg-epns** [ethereum-push-notification-service/push-dapp#701]
- The inbox page is not scrollable, hence, some notifications are getting clipped off from the UI and aren't visible.

<img width="1429" alt="Screenshot 2023-01-16 at 5 45 05 PM" src="https://user-images.githubusercontent.com/110709012/212676011-332253eb-82b7-4349-a63b-d368bd13436a.png">

**Comment by zaryab2000** [comment]
@madhurg-epns  - https://github.com/ethereum-push-notification-service/push-dapp/pull/705#issuecomment-1396867631
