### ISSUE TITLE
fix The Graph logo on subgraph notifications

### ISSUE THREAD

**Issue by aiswaryawalter** [ethereum-push-notification-service/push-dapp#709]
The Graph logo on the top right corner for subgraph-based notifications seems to be out of proportion

<img width="966" alt="Screen Shot 2023-01-19 at 12 54 52 PM" src="https://user-images.githubusercontent.com/66365091/213431586-cb6d3344-21df-4fd6-bf9b-8f80e4ed026b.png">

**Comment by mishramonalisha76** [comment]
this has to be done from the sdk
