### ISSUE TITLE
Add request section for group chat and functionality for accepting intent

### ISSUE THREAD

**Issue by mishramonalisha76** [ethereum-push-notification-service/push-dapp#756]

**Comment by mishramonalisha76** [comment]
https://www.figma.com/file/PzAmXUMOmwS2ljxufwv44m/PUSH-Prototypes?node-id=8081%3A17979&t=jvSY31GQp3vREzZt-0

The message has to be **You were invited to the group <group_name>. Please accept to continue messaging in this group.**

**Comment by mishramonalisha76** [comment]
EOD - 10/02/23 first half

**Comment by abhishek-01k** [comment]
This is done and pushed to the branch - group-chat-feature
