### ISSUE TITLE
Implement add and remove admin  and remove members

### ISSUE THREAD

**Issue by mishramonalisha76** [ethereum-push-notification-service/push-dapp#760]
https://www.figma.com/file/PzAmXUMOmwS2ljxufwv44m/PUSH-Prototypes?node-id=5424%3A6656&t=jvSY31GQp3vREzZt-0

**Comment by mishramonalisha76** [comment]
ETA- 16 feb

**Comment by zaryab2000** [comment]
@abhishek-01k mentioned this is now implemented . Need your confirmation to close this one @mishramonalisha76 ?

**Comment by mishramonalisha76** [comment]
@zaryab2000 , will close it by today
