### ISSUE TITLE
UI fixes in edit channel functionality

### ISSUE THREAD

**Issue by madhurg-epns** [ethereum-push-notification-service/push-dapp#815]
- We should increase the margin a bit on top of the verifying transaction loader.
- Edit channel btn is coming over the heading.
- In mobile view, there is some extra space over the channel edit fee container.

<img width="1429" alt="Screenshot 2023-02-17 at 3 27 20 PM" src="https://user-images.githubusercontent.com/110709012/219616223-7a95dfcf-98c3-4227-b85f-c673d6f8b5d7.png">
<img width="1429" alt="Screenshot 2023-02-17 at 3 27 02 PM" src="https://user-images.githubusercontent.com/110709012/219616227-adf20dc5-0910-4d36-9605-f48c4e223389.png">
<img width="1429" alt="Screenshot 2023-02-17 at 3 26 55 PM" src="https://user-images.githubusercontent.com/110709012/219616234-09d5cdfe-36da-4ff2-8c7c-4e64cc194c3a.png">

<img width="1429" alt="Screenshot 2023-02-17 at 3 37 48 PM" src="https://user-images.githubusercontent.com/110709012/219616186-02b1c871-03e1-47a1-ad47-1c6ca4b5b671.png">
<img width="1429" alt="Screenshot 2023-02-17 at 3 27 42 PM" src="https://user-images.githubusercontent.com/110709012/219616205-567576b1-33c8-4046-8329-ad0b00e9c361.png">

**Comment by zaryab2000** [comment]
@abhishek-01k - believe these issues have been addressed in this PR - https://github.com/ethereum-push-notification-service/push-dapp/pull/881

Kindly check
