### ISSUE TITLE
🚀 [New Feature] - Implement global context for chat

### ISSUE THREAD

**Issue by HarshRajat** [ethereum-push-notification-service/push-dapp#956]
### Describe the Feature

Rationale: Current chat require user to re-login again when they navigate the tab away. Moving to the upmost context should resolve this

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by abhishek-01k** [comment]
In the dev app when a user switches the routes (go to /channels and then again come to /chat) they will not see the metamask pop-up about decrypt request. We can close this issue as this is already present in dApp
@HarshRajat @zaryab2000
