### ISSUE TITLE
😈 [Feature Enhancement] - Add information of limit of amount of groups and messages in w2w

### ISSUE THREAD

**Issue by 0xNilesh** [ethereum-push-notification-service/push-dapp#984]
### Feature name

Chat

### Describe the Enhancement

Max messages in W2W = 1000
Max Groups that can be created = 10

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by KlausMikhaelson** [comment]
Hey @0xNilesh would like to work on it if it's open for others !,
Thank you !

**Comment by 0xNilesh** [comment]
Hey @KlausMikhaelson this issue is complete in a separate PR that's merged, thanks for asking for the contribution
you can look into other issues in this repo, there are plenty of them available

**Comment by KlausMikhaelson** [comment]
@0xNilesh nw, awesome will check it out !
Thank you !
